---
# tasks file for changeUbuntuFirwall

- name: "Deny the IP's"
  ufw:
    rule: deny
    proto: tcp
    port: "{{ item }}"
    src: "{{ ipToDeny }}"
    comment: Changes made by ansible
  loop: "{{ ports }}"

- name: "Display the Status"
  shell: sudo ufw status numbered
  register : outputDeny

- debug: var=outputDeny.stdout_lines

- name : "Allow the IP's"
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
    src: "{{ ipToAllow }}"
    comment: Changes done by Ansible
  loop: "{{ ports }}"

- name: "Display the Status"
  shell : 'sudo ufw show added'
  register : outputAllow

- debug: var=outputAllow.stdout_lines

