---
# tasks file for changeUbuntuFirwall
- name: "Deny the IP's"
  ufw:
    rule: deny
    proto: tcp
    port: "{{ port1 }}"
    src: "{{ ipToDeny }}"
    comment: Changes made by ansible

- name: "Display the Status"
  shell: sudo ufw show added
  register : output

- debug: var=output.stdout_lines

- name : "Allow the IP's"
  ufw:
    rule: allow
    proto: tcp
    port: "{{ port1 }}"
    src: "{{ ipToAllow }}"
    comment: Changes done by Ansible

- name: "Display the Status"
  shell : 'sudo ufw show added'
  register : output

- debug: var=output.stdout_lines

